"""Shared pytest fixtures.

Schema is built via db.create_all() against a fresh temp-file SQLite DB
per test — NOT through Alembic. This is a deliberate choice, not a
shortcut: the SQLAlchemy model classes (CheckConstraint/UniqueConstraint/
Enum definitions) are the single source of truth Alembic's 0001 migration
was autogenerated from, so create_all() exercises the exact same
constraints, just faster and fully isolated per test — no need to spin up
the migration runner for model/constraint-level unit tests.

A temp *file* (via pytest's tmp_path), not sqlite:///:memory:, specifically
to avoid the classic gotcha where each new connection to an in-memory
SQLite DB gets its own empty database unless a single connection is pinned
via StaticPool. A temp file sidesteps that entirely, and tmp_path is
already function-scoped, so every test gets a fully isolated DB for free.
"""

from datetime import UTC, datetime, timedelta

import pytest
from flask_jwt_extended import create_access_token

from app import create_app
from app.config import Config
from app.extensions import db as _db
from app.models import Event, User


@pytest.fixture()
def app(tmp_path):
    class TestConfig(Config):
        SQLALCHEMY_DATABASE_URI = f"sqlite:///{tmp_path / 'test.db'}"
        # Isolates uploaded/re-encoded test images from the real
        # solution/backend/uploads/events/ folder — without this, image
        # upload tests would write real files into the dev/seeded upload
        # directory.
        UPLOAD_FOLDER = str(tmp_path / "uploads" / "events")
        TESTING = True
        # Long enough to avoid PyJWT's InsecureKeyLengthWarning noise in
        # test output — the real dev-only default in .env.example is
        # intentionally short/memorable and doesn't need this.
        JWT_SECRET_KEY = "test-secret-key-thats-long-enough-for-hs256"

    application = create_app(config_class=TestConfig, init_db=True)
    yield application

    with application.app_context():
        _db.session.remove()
        _db.drop_all()
        _db.engine.dispose()  # closes the sqlite connection; avoids a
        # ResourceWarning: unclosed database when many per-test engines
        # accumulate across a full test run.


@pytest.fixture()
def session(app):
    with app.app_context():
        yield _db.session


@pytest.fixture()
def client(app):
    return app.test_client()


@pytest.fixture()
def make_user(session):
    _counter = {"n": 0}

    def _make(**overrides):
        _counter["n"] += 1
        defaults = dict(
            first_name="Test",
            last_name="User",
            email=f"test.user{_counter['n']}@company.com",
            is_admin=False,
        )
        user = User(**{**defaults, **overrides})
        session.add(user)
        session.commit()
        return user

    return _make


@pytest.fixture()
def make_event(session):
    _counter = {"n": 0}

    def _make(**overrides):
        _counter["n"] += 1
        now = datetime.now(UTC).replace(tzinfo=None)
        defaults = dict(
            title=f"Sample Event {_counter['n']}",
            start=now + timedelta(days=7),
            end=now + timedelta(days=7, hours=1),
            spots=5,
            event_type="workshop",
            location_type="in_person",
        )
        event = Event(**{**defaults, **overrides})
        session.add(event)
        session.commit()
        return event

    return _make


@pytest.fixture()
def make_token(app):
    def _make(user) -> str:
        with app.app_context():
            return create_access_token(
                identity=str(user.id),
                additional_claims={"email": user.email, "is_admin": user.is_admin},
            )

    return _make


@pytest.fixture()
def auth_headers(make_token):
    def _headers(user) -> dict:
        return {"Authorization": f"Bearer {make_token(user)}"}

    return _headers
